# ---- TOOL ----
tool_json:                              
  get_current_time: config/tools/web/get_current_time.json
  get_current_weather: config/tools/web/get_current_weather.json

tool_exec:
  get_current_time: config/tools/web/get_current_time.sh
  get_current_weather: config/tools/web/get_current_weather.sh