# ---- TOOL ----
tool_json:                               
  fs_cat: config/tools/fso/fs_cat.json
  fs_ls: config/tools/fso/fs_ls.json
  fs_mkdir: config/tools/fso/fs_mkdir.json

tool_exec:
  fs_cat: config/tools/fso/fs_cat.sh
  fs_ls: config/tools/fso/fs_ls.sh
  fs_mkdir: config/tools/fso/fs_mkdir.sh
